services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es01
    ports:
      - "9200:9200"
    volumes:
      - ./elastic/data:/usr/share/elasticsearch/data
      - ./elastic/logs:/usr/share/elasticsearch/logs
    networks:
      - dashboard_secu
    environment:
      - cluster.name=cluster_name
      - network.host=0.0.0.0
      - ELASTIC_PASSWORD=1234
      - xpack.security.enabled=false
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kb01
    ports:
      - "5601:5601"
    networks:
      - dashboard_secu
    depends_on:
      - elasticsearch

  shiny:
    build: ./shiny
    container_name: sn01
    ports:
      - "8181:8180"
    volumes:
      - ./shiny:/home/shiny-app
    networks:
      - dashboard_secu

networks:
  dashboard_secu: {}